Move to  aggie experts project.  (#259)

diff --git a/bin/aggie-experts b/bin/aggie-experts
--- a/bin/aggie-experts
+++ b/bin/aggie-experts
@@ -78,8 +78,6 @@ declare -g -A G=(
   [dry-run]=
 );
 
-#G[gcloud_user]=$(gcloud auth list --filter="status:ACTIVE"  --format="value(account)")
-
 function G() {
   expand < ${G[config]} | jq "${G[jq]}" | jq -r "$*"
 }
@@ -457,10 +455,10 @@ function setup() {
       dev | clean )
         deploy=dev
         ;;
-      sandbox )
+      sandbox | test)
         deploy=sandbox
         ;;
-      test | prod )
+      prod )
         deploy=prod
         ;;
       *)
@@ -470,7 +468,7 @@ function setup() {
     esac
 
 
-    local secret=$(basename $(gcloud --format=json secrets list --filter="labels.project:${G[project]} AND labels.type:env AND labels.deploy:$deploy" | jq -r '.[0].name'))
+    local secret=$(basename $(gcloud --format=json secrets list --filter="labels.type:env AND labels.deploy:$deploy" | jq -r '.[0].name'))
 
     gcloud secrets versions access latest --secret="$secret"
 
@@ -481,7 +479,7 @@ function setup() {
     echo "GCS=$gcs"
   }
   function service_account() {
-  local service_account=$(basename $(gcloud --format=json secrets list --filter="labels.project:${G[project]} AND labels.type:service-account" | jq -r '.[0].name'))
+  local service_account=$(basename $(gcloud --format=json secrets list --filter="labels.type:service-account-key" | jq -r '.[0].name'))
 
   gcloud secrets versions access latest --secret="$service_account"
 }
@@ -651,6 +649,10 @@ function main.cmd() {
           # Guess env if not supplied
           if [[ -z ${G[env]} ]]; then
             G[env]=$(guess_env)
+            if [[ $? -ne 0 ]]; then
+              >&2 echo "ERROR: Unable to guess one env: $G[env]"
+              exit 1
+            fi
           fi
 
           test_env
