Updated to fin 2.3.0

diff --git a/cmds/aggie-experts b/cmds/aggie-experts
--- a/cmds/aggie-experts
+++ b/cmds/aggie-experts
@@ -77,18 +77,17 @@ function build() {
   local tag
   local N=${G[noop]};
 
-  if [[ "$(G .env)" != "dev" ]]; then
-    echo "You can only build in dev environment"
-    exit 1
-  fi
-
-  declare -a services=(init fcrepo base-service)
-  if [[ "$(G .git.tag)" =~ "dirty" || "$(G .env)" == "dev" ]]; then
+  if [[ "$(G .env)" =~ "dev" ]]; then
     org=localhost/aggie-experts
     tag=dirty
   else
     org=$(G .experts.org)
     tag=$(G .git.tag)
+  fi
+  declare -a services=(init base-service)
+  if [[ "$(G .git.tag)" =~ "dirty" && "$(G .env)" != "dev" ]]; then
+    echo "Cannot build dirty image in non-dev environment"
+    exit 1
   fi
 
   for service in "${services[@]}"; do
